name: GitHub Metrics

on:
  schedule: [{cron: "0 6 * * *"}]  # Runs daily at 6 AM UTC
  workflow_dispatch:
    push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: jordi-adame
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles

          base: "header, repositories, activity, community"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          
