name: GitHub Metrics

on:
  schedule: [{cron: "0 6 * * *"}]  # Runs daily at 6 AM UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: jordi-adame
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles

          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_output: github-yearly-summary.svg
          
          
