name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: jordi-adame
          template: classic
          base: header, repositories, activity, community, metadata
          config_timezone: America/Los_Angeles
