name: GitHub Metrics

on:
  schedule: [{cron: "0 6 * * *"}]  # Runs daily at 6 AM UTC
  workflow_dispatch:


jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: jordi-adame
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles

          base: header, activity, community, repositories, metadata
          
          plugin_languages: yes
          plugin_achievements: yes
          plugin_lines: yes
          plugin_habits: yes
          plugin_isocalendar: yes
          plugin_calendar: yes
          plugin_followup: yes
          plugin_topics: yes
          plugin_traffic: yes
          plugin_issue_pr_lang: yes
